services:
  _defaults:
    public: true
  prestashop.module.sc_admin_edits.form.type.admin_edits_configuration_text:
    class: 'PrestaShop\Module\Sc_Admin_Edits\Form\AdminEditsConfigurationTextType'
    parent: 'form.type.translatable.aware'
    calls:
            - [setLegacyConfiguration, ['@prestashop.adapter.legacy.configuration']]
    public: true
    tags:
      - { name: form.type }

  prestashop.module.sc_admin_edits.form.admin_edits_configuration_text_form_data_provider:
    class: 'PrestaShop\Module\Sc_Admin_Edits\Form\AdminEditsConfigurationTextFormDataProvider'
    arguments:
      - '@prestashop.module.sc_admin_edits.form.admin_edits_configuration_text_data_configuration'

  prestashop.module.sc_admin_edits.form.admin_edits_configuration_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.sc_admin_edits.form.admin_edits_configuration_text_form_data_provider'
      - 'PrestaShop\Module\Sc_Admin_Edits\Form\AdminEditsConfigurationTextType'
      - 'AdminEditsConfiguration'

  prestashop.module.sc_admin_edits.form.admin_edits_configuration_text_data_configuration:
    class: PrestaShop\Module\Sc_Admin_Edits\Form\AdminEditsConfigurationTextDataConfiguration
    arguments: ['@prestashop.adapter.legacy.configuration']